#!/usr/bin/env python3
# Sway Snip by Zuma206
# Licensed under the GPLv3
import subprocess
import shutil

# Check that the required dependancies are installed for a given function
def dependancies(*dependancies):
  def decorator(func):
    for dependancy in dependancies:
      if shutil.which(dependancy) is None:
        print(f"Missing dependancy: {dependancy}")
    return func
  return decorator

@dependancies("grim")
def grim():
  proc = subprocess.run(["grim", "-"])
  return proc.stdout

def main():
  print(grim())
  
if __name__ == "__main__":
  main()
